name: Lint the specification file
on: push
jobs:
  docs-release:
    runs-on: ubuntu-latest
    steps:
    - name: Spectral checks
      uses: XVincentX/spectral-action@v0.3.0
      env:
        SPECTRAL_FILE_PATH: api.json
